export const MOBILE_BREAKPOINT = 768
export const DOCS_LINK = 'https://github.com/skymavis/tanto-kit/blob/main/packages/widget/README.md'
export const REPO_LINK = 'https://github.com/skymavis/tanto-kit'
export const BUY_CRYPTO_DOCS_LINK = 'https://docs.skymavis.com/mavis/ronin-waypoint/reference/web-utilities-sdk'
export const SUPPORTED_CRYPTOCURRENCIES = [
  { key: 'RON', label: 'Ronin', value: 'RON' },
  { key: 'AXS', label: 'Axie Infinity Shard', value: 'AXS' },
  { key: 'SLP', label: 'Smooth Love Potion', value: 'SLP' },
  { key: 'USDC', label: 'USD Coin', value: 'USDC' },
  { key: 'WETH', label: 'Ronin Wrapped Ether', value: 'WETH' },
  { key: 'PIXEL', label: 'PIXEL', value: 'PIXEL' },
  { key: 'BANANA', label: 'BANANA', value: 'BANANA' },
  { key: 'APRS', label: 'Apeiros', value: 'APRS' },
]
export const SUPPORTED_FIAT_CURRENCIES = [
  { key: 'USD', label: 'US Dollar', value: 'USD' },
  { key: 'GBP', label: 'British Pound', value: 'GBP' },
  { key: 'INR', label: 'Indian Rupee', value: 'INR' },
  { key: 'EUR', label: 'Euro', value: 'EUR' },
  { key: 'CHF', label: 'Swiss Franc', value: 'CHF' },
  { key: 'SEK', label: 'Swedish Krona', value: 'SEK' },
  { key: 'PLN', label: 'Polish Zloty', value: 'PLN' },
  { key: 'NOK', label: 'Norwegian Krone', value: 'NOK' },
  { key: 'DKK', label: 'Danish Krone', value: 'DKK' },
  { key: 'NZD', label: 'New Zealand Dollar', value: 'NZD' },
  { key: 'MXN', label: 'Mexican Peso', value: 'MXN' },
  { key: 'CAD', label: 'Canadian Dollar', value: 'CAD' },
  { key: 'AUD', label: 'Australian Dollar', value: 'AUD' },
  { key: 'ARS', label: 'Argentine Peso', value: 'ARS' },
  { key: 'BRL', label: 'Brazilian Real', value: 'BRL' },
  { key: 'CLP', label: 'Chilean Peso', value: 'CLP' },
  { key: 'CRC', label: 'Costa Rican Colon', value: 'CRC' },
  { key: 'DOP', label: 'Dominican Peso', value: 'DOP' },
  { key: 'IDR', label: 'Indonesian Rupiah', value: 'IDR' },
  { key: 'ILS', label: 'Israeli Shekel', value: 'ILS' },
  { key: 'JPY', label: 'Japanese Yen', value: 'JPY' },
  { key: 'KRW', label: 'South Korean Won', value: 'KRW' },
  { key: 'MYR', label: 'Malaysian Ringgit', value: 'MYR' },
  { key: 'PYG', label: 'Paraguayan Guarani', value: 'PYG' },
  { key: 'PEN', label: 'Peruvian Sol', value: 'PEN' },
  { key: 'PHP', label: 'Philippine Peso', value: 'PHP' },
  { key: 'SGD', label: 'Singapore Dollar', value: 'SGD' },
  { key: 'FJD', label: 'Fiji Dollar', value: 'FJD' },
  { key: 'HUF', label: 'Forint', value: 'HUF' },
  { key: 'KES', label: 'Kenyan Shilling', value: 'KES' },
  { key: 'MDL', label: 'Moldovan Leu', value: 'MDL' },
  { key: 'BMD', label: 'Bermudian Dollar', value: 'BMD' },
  { key: 'FKP', label: 'Falkland Islands Pound', value: 'FKP' },
  { key: 'CZK', label: 'Czech Koruna', value: 'CZK' },
  { key: 'ISK', label: 'Iceland Krona', value: 'ISK' },
  { key: 'RON', label: 'Romanian Leu', value: 'RON' },
  { key: 'AOA', label: 'Kwanza', value: 'AOA' },
  { key: 'BZD', label: 'Belize Dollar', value: 'BZD' },
  { key: 'BND', label: 'Brunei Dollar', value: 'BND' },
  { key: 'KMF', label: 'Comoro Franc', value: 'KMF' },
  { key: 'DJF', label: 'Djibouti Franc', value: 'DJF' },
  { key: 'XCD', label: 'East Caribbean Dollar', value: 'XCD' },
  { key: 'GEL', label: 'Lari', value: 'GEL' },
  { key: 'GTQ', label: 'Quetzal', value: 'GTQ' },
  { key: 'HNL', label: 'Lempira', value: 'HNL' },
  { key: 'HKD', label: 'Hong Kong Dollar', value: 'HKD' },
  { key: 'KZT', label: 'Tenge', value: 'KZT' },
  { key: 'KGS', label: 'Som', value: 'KGS' },
  { key: 'MGA', label: 'Malagasy Ariary', value: 'MGA' },
  { key: 'MWK', label: 'Kwacha', value: 'MWK' },
  { key: 'MRU', label: 'Ouguiya', value: 'MRU' },
  { key: 'OMR', label: 'Rial Omani', value: 'OMR' },
  { key: 'PGK', label: 'Kina', value: 'PGK' },
  { key: 'RWF', label: 'Rwanda Franc', value: 'RWF' },
  { key: 'STN', label: 'Dobra', value: 'STN' },
  { key: 'SCR', label: 'Seychelles Rupee', value: 'SCR' },
  { key: 'SBD', label: 'Solomon Islands Dollar', value: 'SBD' },
  { key: 'SRD', label: 'Surinam Dollar', value: 'SRD' },
  { key: 'SZL', label: 'Lilangeni', value: 'SZL' },
  { key: 'TJS', label: 'Somoni', value: 'TJS' },
  { key: 'TOP', label: 'Pa’anga', value: 'TOP' },
  { key: 'TMT', label: 'Turkmenistan New Manat', value: 'TMT' },
  { key: 'UYU', label: 'Peso Uruguayo', value: 'UYU' },
  { key: 'COP', label: 'Colombian Peso', value: 'COP' },
  { key: 'TWD', label: 'Taiwanese Dollar', value: 'TWD' },
  { key: 'GHS', label: 'Ghanaian Cedi', value: 'GHS' },
  { key: 'AED', label: 'UAE Dirham', value: 'AED' },
  { key: 'KHR', label: 'Cambodian Riel', value: 'KHR' },
  { key: 'RSD', label: 'Serbian Dinar', value: 'RSD' },
  { key: 'BHD', label: 'Bahraini Dinar', value: 'BHD' },
  { key: 'MKD', label: 'Macedonian Denar', value: 'MKD' },
  { key: 'KWD', label: 'Kuwaiti Dinar', value: 'KWD' },
  { key: 'AMD', label: 'Armenian Dram', value: 'AMD' },
  { key: 'ANG', label: 'Netherlands Antilles Guilder', value: 'ANG' },
  { key: 'AZN', label: 'Azerbaijani Manat', value: 'AZN' },
  { key: 'BSD', label: 'Bahamian Dollar', value: 'BSD' },
  { key: 'KYD', label: 'Cayman Islands Dollar', value: 'KYD' },
  { key: 'CVE', label: 'Cape Verdean Escudo', value: 'CVE' },
  { key: 'BAM', label: 'BH Convertible Mark', value: 'BAM' },
  { key: 'JOD', label: 'Jordanian Dinar', value: 'JOD' },
  { key: 'TTD', label: 'Trinidad & Tobago Dollar', value: 'TTD' },
  { key: 'PAB', label: 'Panamanian Balboa', value: 'PAB' },
  { key: 'DZD', label: 'Algerian Dinar', value: 'DZD' },
  { key: 'BGN', label: 'Bulgarian Lev', value: 'BGN' },
  { key: 'EGP', label: 'Egyptian Pound', value: 'EGP' },
  { key: 'LKR', label: 'Sri Lankan Rupee', value: 'LKR' },
  { key: 'NGN', label: 'Nigerian Naira', value: 'NGN' },
  { key: 'THB', label: 'Thai Baht', value: 'THB' },
  { key: 'TRY', label: 'Turkish Lira', value: 'TRY' },
  { key: 'VND', label: 'Vietnamese Dong', value: 'VND' },
  { key: 'ZAR', label: 'South African Rand', value: 'ZAR' },
  { key: 'BWP', label: 'Botswana Pula', value: 'BWP' },
  { key: 'MZN', label: 'Mozambican Metical', value: 'MZN' },
  { key: 'LAK', label: 'Lao Kip', value: 'LAK' },
]
